name: Lint and test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci
      - run: npm run build

      - run: npm run lint
      - run: npm run typecheck

      - name: Run tests and collect coverage
        run: npm run test:coverage
