name: Build and publish ts-tools

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/tools/**"

jobs:
  build_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      workspace: packages/tools
      depends_on: packages/types
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
